# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech4goodbristol.gihub.io" # the base hostname & protocol for your site


# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "utils"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Build settings
markdown: kramdown

permalink: pretty

collections:
    shout_outs:
      output: true
      permalink: /shout-outs/:path
    posts:
      output: true
      permalink: /:year-:month-:day/:title

defaults:
  - scope:
      path: ""
      type: shout_outs
    values:
      layout: shout-out

include: ['_pages']